lecture05
yosuke389559/RaiseTech pull request #5
Opened 2023-06-04 12:57 UTC by yosuke389559

第５回課題を提出します。
・　puma単体でのサンプルアプリ起動
・　unicorn単体でのサンプルアプリ起動
・　nginxの起動
・　unicornとnginxのサーバーを分けてのサンプルアプリ起動
・　unicornとnginxのサーバーを分けて、ALBを追加した状態でのサンプルアプリ起動
・　S3を作成して、サンプルアプリの画像保存先として利用
・　構成図の作成
が主な作業となっています。
ご確認よろしくお願いいたします。

2023-06-04 14:52 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応ください！

2023-06-04 14:52 UTC, MasatoshiMizumoto commented on lec05/image/ALBーTargetgroup.png
Unhealtyでスクショ撮られてるので取り直したほうが良いかもです！

2023-06-04 14:52 UTC, MasatoshiMizumoto commented on lec05/lecture05.md
画像は各セクションに埋め込んでいただいたほうが見やすいので実施いただきたいです！

2023-06-05 21:46 UTC, yosuke389559 commented
ヘルスチェック結果の画像
各セクションへの画像埋め込み
完了しました。
ご確認よろしくお願いいたします。

2023-06-05 23:38 UTC, MasatoshiMizumoto requested changes
画像変わってなさそうなのでご確認いただきたいです！

2023-06-05 23:38 UTC, MasatoshiMizumoto commented on lec05/image/ALBーTargetgroup.png
変わってなさそうです！

2023-06-05 23:56 UTC, yosuke389559 commented
失礼しました、該当画像を再度訂正しました。
よろしくお願いします。

2023-06-06 14:40 UTC, yosuke389559 commented
ヘルスチェックに関する画像を変更。

2023-06-06 14:46 UTC, yosuke389559 commented
commit4をご確認お願いします！

2023-06-06 14:59 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-06-07 00:59 UTC, merged